openapi: 3.0.0
info:
  title: M3_ServerCertificatesProvisioning
  version: 0.0.0
  description: |
    5GMS AS M3 Server Certificates Provisioning API
    Copyright © 2022 British Broadcasting Corporation
    All rights reserved.
tags:
  - name: M3_ServerCertificatesProvisioning
    description: '5G Media Streaming: Application Server Provisioning (M3) APIs: Server Certificates Provisioning'
externalDocs:
  description: 'TS 26.512 V16.x.x; 5G Media Streaming (5GMS); Protocols'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/'
servers:
  - url: '{apiRoot}/3gpp-m3/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: See 3GPP TS 29.512 clause 6.1.
paths:
  /certificates:
    summary: "Server Certificates collection"
    get:
      operationId: retrieveServerCertificates
      summary: "Retrieve a list of Server Certificate composite resource identifiers currently registered with the 5GMS AS"
      responses:
        '200':
          # OK
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /certificates/{afUniqueCertificateId}:
    summary: "Operations to manipulate a single Server Certificate resource"
    description: "Individual Server Certificate resources in the collection are addressed using a unique certificateId generated by the 5GMS AF which is guarenteed to be unique across all provisioning sessions."
    parameters:
     - name: afUniqueCertificateId
       in: path
       required: true
       schema:
         $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
       description: 'The unique identifier, assigned by the 5GMS AF, for a certificate. This is unique across all certificates for all provisioning sessions.'
    post:
      operationId: createServerCertificate
      summary: "Create a new Server Certificate resource and upload an X.509 certificate bundle to be associated with it"
      requestBody:
        description: "As well as the public certificate itself, the PEM bundle is required to include the private key of the certificate and any intermediate CA certificates."
        required: true
        content:
          application/x-pem-file:
            schema:
              type: string
      responses:
        '201':
          # Created
          description: "Server Certificate Created"
          headers:
            Location:
              description: 'URL of the newly created Content Hosting Configuration (which may be redirected from the request URL).'
              required: true
              schema:
                $ref: 'TS26512_CommonData.yaml#/components/schemas/Url'
        '405':
          # Method Not Allowed: Server Certificate resource already exists at the specified path
          $ref: 'TS29571_CommonData.yaml#/components/responses/405'
        '413':
          # Payload too large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI too long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'    
    # (Retrieval of individual Server Certificate resources is not permitted at reference point M3.)
    put:
      operationId: updateServerCertificate
      summary: "Update (by replacement) an existing Server Certificate resource with a new X.509 certificate bundle"
      requestBody:
        description: "As well as the public certificate itself, the PEM bundle is required to include the private key of the certificate and any intermediate CA certificates."
        required: true
        content:
          application/x-pem-file:
            schema:
              type: string
      responses:
        '200':
          # OK
          description: "Server Certificate Updated"
        '204':
          # No Content
          description: 'Server Certificate Unchanged'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '413':
          # Payload too large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI too long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default' 
    delete:
      operationId: destroyServerCertificate
      summary: 'Destroy an existing Server Certificate resource'
      responses:
        '204':
          # No Content
          description: 'Server Certificate Destroyed'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '409':
          # Conflict
          $ref: 'TS29571_CommonData.yaml#/components/responses/409'
        '413':
          # Payload too large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI too long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
