enablePostProcessFile: true
templateDir: "."
reservedWordsMappings:
  3GPP_ACCESS: "3GPP_ACCESS"
  5G_EIR: "5G_EIR"
  5G_AKA: "5G_AKA"
  5G_HE_AKA: "5G_HE_AKA"
  5GMM: "5GMM"
files:
  AnyType.hh:
    folder: model
  AnyType.h:
    folder: model
  Boundary.hh:
    folder: model
  CJson.cc:
    folder: model
  CJson.hh:
    folder: model
  ModelException.hh:
    folder: model
  ModelObject.hh:
    folder: model
  OgsAllocator.cc:
    folder: model
  OgsAllocator.hh:
    folder: model
  Validator.hh:
    folder: model
  model-header.mustache:
    templateType: Model
    folder: model
    destinationFilename: .h
  model-source.mustache:
    templateType: Model
    folder: model
    destinationFilename: .cc
  model-json.mustache:
    templateType: Model
    folder: model
    destinationFilename: .json
